// This file was generated by the following script:
//
//   $ ./src/acetimetools/tzcompiler.py
//     --input_dir /Users/andy/code/dbc/main/3rdparty/AceTimeTools/tzfiles
//     --output_dir /Users/andy/code/dbc/main/3rdparty/AceTimeTools
//     --tz_version HEAD
//     --tz_version 2024a
//     --actions zonedb
//     --languages c
//     --scope complete
//     --db_namespace Atc
//     --start_year 2024
//     --until_year 2028
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2024a
//
// Supported Zones: 596 (351 zones, 245 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [2024,2028]
// Accurate Years: [2024,2028]
//
// Original Years:  [1844,2087]
// Generated Years: [1967,2028]
// Lower/Upper Truncated: [True,True]
//
// Estimator Years: [1967,2029]
// Max Buffer Size: 6
//
// Records:
//   Infos: 596
//   Eras: 358
//   Policies: 67
//   Rules: 153
//
// Memory (8-bits):
//   Context: 16
//   Rules: 1836
//   Policies: 201
//   Eras: 5370
//   Zones: 4563
//   Links: 3185
//   Registry: 1192
//   Formats: 510
//   Letters: 35
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 25984
//
// Memory (32-bits):
//   Context: 24
//   Rules: 1836
//   Policies: 536
//   Eras: 7160
//   Zones: 8424
//   Links: 5880
//   Registry: 2384
//   Formats: 510
//   Letters: 49
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 35879
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ATC_ZONE_POLICIES_H
#define ACE_TIME_C_ZONEDB_ATC_ZONE_POLICIES_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

//---------------------------------------------------------------------------
// Supported policies: 67
//---------------------------------------------------------------------------

extern const AtcZonePolicy kAtcZonePolicyAN;
extern const AtcZonePolicy kAtcZonePolicyAQ;
extern const AtcZonePolicy kAtcZonePolicyAS;
extern const AtcZonePolicy kAtcZonePolicyAT;
extern const AtcZonePolicy kAtcZonePolicyAV;
extern const AtcZonePolicy kAtcZonePolicyAW;
extern const AtcZonePolicy kAtcZonePolicyArg;
extern const AtcZonePolicy kAtcZonePolicyArmenia;
extern const AtcZonePolicy kAtcZonePolicyAus;
extern const AtcZonePolicy kAtcZonePolicyAzer;
extern const AtcZonePolicy kAtcZonePolicyBarb;
extern const AtcZonePolicy kAtcZonePolicyBelize;
extern const AtcZonePolicy kAtcZonePolicyBrazil;
extern const AtcZonePolicy kAtcZonePolicyC_Eur;
extern const AtcZonePolicy kAtcZonePolicyCO;
extern const AtcZonePolicy kAtcZonePolicyCR;
extern const AtcZonePolicy kAtcZonePolicyCanada;
extern const AtcZonePolicy kAtcZonePolicyChatham;
extern const AtcZonePolicy kAtcZonePolicyChile;
extern const AtcZonePolicy kAtcZonePolicyCook;
extern const AtcZonePolicy kAtcZonePolicyCuba;
extern const AtcZonePolicy kAtcZonePolicyDhaka;
extern const AtcZonePolicy kAtcZonePolicyEU;
extern const AtcZonePolicy kAtcZonePolicyEUAsia;
extern const AtcZonePolicy kAtcZonePolicyEcuador;
extern const AtcZonePolicy kAtcZonePolicyEgypt;
extern const AtcZonePolicy kAtcZonePolicyEire;
extern const AtcZonePolicy kAtcZonePolicyFiji;
extern const AtcZonePolicy kAtcZonePolicyGuat;
extern const AtcZonePolicy kAtcZonePolicyHK;
extern const AtcZonePolicy kAtcZonePolicyHaiti;
extern const AtcZonePolicy kAtcZonePolicyHoliday;
extern const AtcZonePolicy kAtcZonePolicyHond;
extern const AtcZonePolicy kAtcZonePolicyIran;
extern const AtcZonePolicy kAtcZonePolicyIraq;
extern const AtcZonePolicy kAtcZonePolicyJapan;
extern const AtcZonePolicy kAtcZonePolicyLH;
extern const AtcZonePolicy kAtcZonePolicyLebanon;
extern const AtcZonePolicy kAtcZonePolicyMacau;
extern const AtcZonePolicy kAtcZonePolicyMauritius;
extern const AtcZonePolicy kAtcZonePolicyMexico;
extern const AtcZonePolicy kAtcZonePolicyMoldova;
extern const AtcZonePolicy kAtcZonePolicyMongol;
extern const AtcZonePolicy kAtcZonePolicyMorocco;
extern const AtcZonePolicy kAtcZonePolicyNC;
extern const AtcZonePolicy kAtcZonePolicyNZ;
extern const AtcZonePolicy kAtcZonePolicyNamibia;
extern const AtcZonePolicy kAtcZonePolicyNic;
extern const AtcZonePolicy kAtcZonePolicyPRC;
extern const AtcZonePolicy kAtcZonePolicyPakistan;
extern const AtcZonePolicy kAtcZonePolicyPalestine;
extern const AtcZonePolicy kAtcZonePolicyPara;
extern const AtcZonePolicy kAtcZonePolicyPeru;
extern const AtcZonePolicy kAtcZonePolicyPhil;
extern const AtcZonePolicy kAtcZonePolicyROK;
extern const AtcZonePolicy kAtcZonePolicySA;
extern const AtcZonePolicy kAtcZonePolicySalv;
extern const AtcZonePolicy kAtcZonePolicyTaiwan;
extern const AtcZonePolicy kAtcZonePolicyThule;
extern const AtcZonePolicy kAtcZonePolicyTonga;
extern const AtcZonePolicy kAtcZonePolicyTroll;
extern const AtcZonePolicy kAtcZonePolicyTunisia;
extern const AtcZonePolicy kAtcZonePolicyUS;
extern const AtcZonePolicy kAtcZonePolicyUruguay;
extern const AtcZonePolicy kAtcZonePolicyVanuatu;
extern const AtcZonePolicy kAtcZonePolicyWS;
extern const AtcZonePolicy kAtcZonePolicyZion;


//---------------------------------------------------------------------------
// Unsupported zone policies: 67
//---------------------------------------------------------------------------

// Albania {unused}
// Algeria {unused}
// Austria {unused}
// Belgium {unused}
// Bermuda {unused}
// Bulg {unused}
// CA {unused}
// Chicago {unused}
// Cyprus {unused}
// Czech {unused}
// DR {unused}
// Denver {unused}
// Detroit {unused}
// E-Eur {unused}
// E-EurAsia {unused}
// Edm {unused}
// EgyptAsia {unused}
// Falk {unused}
// Finland {unused}
// France {unused}
// GB-Eire {unused}
// Germany {unused}
// Greece {unused}
// Guam {unused}
// Halifax {unused}
// Hungary {unused}
// Indianapolis {unused}
// Italy {unused}
// Jordan {unused}
// Kyrgyz {unused}
// Latvia {unused}
// Libya {unused}
// Louisville {unused}
// Malta {unused}
// Marengo {unused}
// Menominee {unused}
// Moncton {unused}
// NBorneo {unused}
// NT_YK {unused}
// NYC {unused}
// Perry {unused}
// Pike {unused}
// Poland {unused}
// Port {unused}
// Pulaski {unused}
// Regina {unused}
// Romania {unused}
// Russia {unused}
// RussiaAsia {unused}
// SanLuis {unused}
// Shang {unused}
// SovietZone {unused}
// Spain {unused}
// SpainAfrica {unused}
// StJohns {unused}
// Starke {unused}
// Sudan {unused}
// Swift {unused}
// Swiss {unused}
// Syria {unused}
// Toronto {unused}
// Turkey {unused}
// Vanc {unused}
// Vincennes {unused}
// W-Eur {unused}
// Winn {unused}
// Yukon {unused}


//---------------------------------------------------------------------------
// Notable zone policies: 6
//---------------------------------------------------------------------------

// Belize {LETTER 'CST' not single character}
// Eire {SAVE '-1:00' is a negative DST}
// LH {SAVE '0:30' different from 1:00}
// Morocco {SAVE '-1:00' is a negative DST}
// Namibia {LETTER 'CAT' not single character}
// Troll {
//   LETTER '+00' not single character,
//   LETTER '+02' not single character,
//   SAVE '2:00' different from 1:00,
// }


//---------------------------------------------------------------------------

#ifdef __cplusplus
}
#endif

#endif
