// This file was generated by the following script:
//
//   $ ./src/acetimetools/tzcompiler.py
//     --input_dir /Users/andy/code/dbc/main/3rdparty/AceTimeTools/tzfiles
//     --output_dir /Users/andy/code/dbc/main/3rdparty/AceTimeTools
//     --tz_version HEAD
//     --tz_version 2024a
//     --actions zonedb
//     --languages c
//     --scope complete
//     --db_namespace Atc
//     --start_year 2024
//     --until_year 2028
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2024a
//
// Supported Zones: 596 (351 zones, 245 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [2024,2028]
// Accurate Years: [2024,2028]
//
// Original Years:  [1844,2087]
// Generated Years: [1967,2028]
// Lower/Upper Truncated: [True,True]
//
// Estimator Years: [1967,2029]
// Max Buffer Size: 6
//
// Records:
//   Infos: 596
//   Eras: 358
//   Policies: 67
//   Rules: 153
//
// Memory (8-bits):
//   Context: 16
//   Rules: 1836
//   Policies: 201
//   Eras: 5370
//   Zones: 4563
//   Links: 3185
//   Registry: 1192
//   Formats: 510
//   Letters: 35
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 25984
//
// Memory (32-bits):
//   Context: 24
//   Rules: 1836
//   Policies: 536
//   Eras: 7160
//   Zones: 8424
//   Links: 5880
//   Registry: 2384
//   Formats: 510
//   Letters: 49
//   Fragments: 0
//   Names: 9076 (original: 9076)
//   TOTAL: 35879
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ATC_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_ATC_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcZoneRegistrySize 351
extern const AtcZoneInfo * const kAtcZoneRegistry[351];

// Zones and Links
#define kAtcZoneAndLinkRegistrySize 596
extern const AtcZoneInfo * const kAtcZoneAndLinkRegistry[596];

#ifdef __cplusplus
}
#endif

#endif
