# See https://docs.github.com/en/actions/guides for documentation about GitHub
# Actions.

name: Unit Tests

# Run on all branches.
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/ACUnit
        git clone https://github.com/bxparks/EpoxyDuino

    - name: Verify examples
      run: |
        make -C examples/arduino/HelloTextClock clean
        make -C examples/arduino/HelloTextClock
        make -C examples/arduino/HelloTextClock clean

    - name: Verify tests
      run: |
        make -C src
        make -C tests
        make -C tests runtests
